name: intershipflutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  table_calendar: ^3.0.9
  flutter_time_picker_spinner: ^2.0.0

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_neumorphic: ^3.2.0
  adaptive_platform_ui: ^0.1.100
  http: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

    - family: Inter-VariableFont_opsz,wght
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf